import json

products = [
    (
        'LAP-001',
        'Apple MacBook Pro 16" M3 Max',
        'Laptops',
        249990.0,
        '₹',
        14,
        'Flagship workstation with 16-core CPU, 40-core GPU, 36GB unified RAM, Liquid Retina XDR display, and 22-hour battery life.',
        '{"processor": "Apple M3 Max 16-Core", "ram": "36GB Unified", "storage": "1TB NVMe SSD", "display": "16.2-inch Liquid Retina XDR 120Hz", "weight": "2.14 kg"}',
        '/images/products/LAP-001.jpg'
    ),
    (
        'LAP-002',
        'Dell XPS 15 OLED InfinityEdge',
        'Laptops',
        154990.0,
        '₹',
        20,
        'Precision-crafted creator laptop with 3.5K OLED touchscreen, Intel Core i7-13700H, and NVIDIA GeForce RTX 4060 graphics.',
        '{"processor": "Intel Core i7-13700H", "ram": "32GB DDR5", "storage": "1TB PCIe Gen4 SSD", "display": "15.6-inch 3.5K OLED Touch", "graphics": "RTX 4060 8GB"}',
        '/images/products/LAP-002.jpg'
    ),
    (
        'LAP-003',
        'Lenovo ThinkPad X1 Carbon Gen 11',
        'Laptops',
        134990.0,
        '₹',
        18,
        'Ultralight business flagship with carbon fiber chassis, legendary spill-resistant keyboard, 14-inch 2.8K OLED, and military-grade durability.',
        '{"processor": "Intel Core i7-1365U vPro", "ram": "16GB LPDDR5", "storage": "512GB SSD", "display": "14-inch 2.8K OLED 400 nits", "weight": "1.12 kg"}',
        '/images/products/LAP-003.jpg'
    ),
    (
        'LAP-004',
        'ASUS ROG Zephyrus G16 Gaming Laptop',
        'Laptops',
        179990.0,
        '₹',
        12,
        'High-performance gaming machine with Intel Core Ultra 9, RTX 4070, 240Hz ROG Nebula OLED display, and CNC aluminum unibody.',
        '{"processor": "Intel Core Ultra 9 185H", "ram": "32GB LPDDR5X", "storage": "2TB NVMe SSD", "display": "16-inch 2.5K OLED 240Hz 0.2ms", "graphics": "RTX 4070 8GB"}',
        '/images/products/LAP-004.jpg'
    ),
    (
        'LAP-005',
        'HP Spectre x360 2-in-1 Convertible',
        'Laptops',
        119990.0,
        '₹',
        22,
        'Versatile 360-degree flip touchscreen laptop with 9MP AI camera, haptic touchpad, rechargeable active stylus, and Intel Evo certification.',
        '{"processor": "Intel Core Ultra 7 155H", "ram": "16GB LPDDR5X", "storage": "1TB SSD", "display": "14-inch 2.8K OLED 120Hz Touch", "battery": "Up to 17 hours"}',
        '/images/products/LAP-005.jpg'
    ),
    (
        'LAP-006',
        'Apple MacBook Air 13" M3',
        'Laptops',
        99990.0,
        '₹',
        30,
        'Strikingly thin fanless design with M3 chip, support for up to two external displays, MagSafe, and 18-hour battery.',
        '{"processor": "Apple M3 8-core", "ram": "16GB Unified", "storage": "512GB SSD", "display": "13.6-inch Liquid Retina", "weight": "1.24 kg"}',
        '/images/products/LAP-006.jpg'
    ),
    (
        'LAP-007',
        'Acer Swift Go 14 AI OLED',
        'Laptops',
        74990.0,
        '₹',
        25,
        'Modern AI-boosted ultrabook with Intel Core Ultra 5, dedicated NPU for Copilot, 90Hz OLED display, and multi-day battery life.',
        '{"processor": "Intel Core Ultra 5 125H", "ram": "16GB LPDDR5X", "storage": "512GB PCIe Gen4", "display": "14-inch 2.8K OLED 90Hz", "npu": "Intel AI Boost"}',
        '/images/products/LAP-007.jpg'
    ),
    (
        'LAP-008',
        'ASUS TUF Gaming A15',
        'Laptops',
        68990.0,
        '₹',
        28,
        'Durable military-grade gaming laptop with AMD Ryzen 7 7735HS, NVIDIA GeForce RTX 3050, 144Hz IPS display, and dual fans.',
        '{"processor": "AMD Ryzen 7 7735HS", "ram": "16GB DDR5", "storage": "512GB NVMe", "display": "15.6-inch FHD 144Hz", "graphics": "RTX 3050 4GB"}',
        '/images/products/LAP-008.jpg'
    ),
    (
        'LAP-009',
        'Lenovo IdeaPad Slim 3 Student Edition',
        'Laptops',
        39990.0,
        '₹',
        40,
        'Reliable lightweight laptop built for students and online work. Features Intel Core i3 12th Gen, anti-glare screen, and privacy shutter.',
        '{"processor": "Intel Core i3-1215U", "ram": "8GB DDR4", "storage": "512GB SSD", "display": "15.6-inch FHD Anti-Glare", "battery": "Up to 8 hours"}',
        '/images/products/LAP-009.jpg'
    ),
    (
        'LAP-010',
        'HP 15s Everyday Budget Laptop',
        'Laptops',
        29990.0,
        '₹',
        50,
        'Budget-friendly everyday laptop for home and office essentials with AMD Athlon Silver, fast charge, and full numeric keypad.',
        '{"processor": "AMD Athlon Silver 7120U", "ram": "8GB LPDDR5", "storage": "256GB SSD", "display": "15.6-inch HD Micro-Edge", "weight": "1.69 kg"}',
        '/images/products/LAP-010.jpg'
    ),
    (
        'PHN-001',
        'Apple iPhone 16 Pro Max 256GB',
        'Phones',
        144900.0,
        '₹',
        18,
        'Grade 5 titanium design with Camera Control button, 4K 120fps Dolby Vision, and industry-leading A18 Pro chip.',
        '{"chip": "A18 Pro Bionic", "ram": "8GB", "storage": "256GB", "camera": "48MP Fusion + 48MP Ultra-wide + 12MP 5x Telephoto", "display": "6.9-inch Super Retina XDR OLED 120Hz"}',
        '/images/products/PHN-001.jpg'
    ),
    (
        'PHN-002',
        'Samsung Galaxy S25 Ultra 5G',
        'Phones',
        129999.0,
        '₹',
        15,
        'The pinnacle of Android engineering with Galaxy AI, titanium frame, 200MP quad camera, and integrated S-Pen stylus.',
        '{"processor": "Snapdragon 8 Elite", "ram": "12GB", "storage": "512GB", "camera": "200MP Main + 50MP Periscope 5x", "display": "6.8-inch Dynamic AMOLED 2X 120Hz", "spen": "Built-in S-Pen"}',
        '/images/products/PHN-002.jpg'
    ),
    (
        'PHN-003',
        'Google Pixel 9 Pro 128GB',
        'Phones',
        109999.0,
        '₹',
        20,
        'Best-in-class computational photography with Gemini AI built-in, 7 years of OS updates, and matte glass finish.',
        '{"chip": "Google Tensor G4 + Titan M2", "ram": "16GB", "storage": "128GB", "camera": "50MP Main + 48MP Ultra + 48MP 5x Tele", "display": "6.3-inch Super Actua OLED 1-120Hz"}',
        '/images/products/PHN-003.jpg'
    ),
    (
        'PHN-004',
        'OnePlus 13 Hasselblad 5G',
        'Phones',
        69999.0,
        '₹',
        25,
        'Speed flagship with 6000mAh silicon-carbon battery, 100W wired + 50W wireless charging, and Hasselblad portrait engine.',
        '{"processor": "Snapdragon 8 Elite", "ram": "16GB LPDDR5X", "storage": "512GB UFS 4.0", "camera": "50MP Sony LYT-808 Hasselblad", "battery": "6000mAh 100W SuperVOOC"}',
        '/images/products/PHN-004.jpg'
    ),
    (
        'PHN-005',
        'Apple iPhone 15 128GB',
        'Phones',
        65999.0,
        '₹',
        30,
        'Dynamic Island, 48MP main camera with 2x optical-quality zoom, USB-C connectivity, and durable color-infused back glass.',
        '{"chip": "A16 Bionic", "ram": "6GB", "storage": "128GB", "camera": "48MP Main + 12MP Ultra-wide", "display": "6.1-inch Super Retina XDR OLED", "port": "USB-C"}',
        '/images/products/PHN-005.jpg'
    ),
    (
        'PHN-006',
        'Samsung Galaxy Z Flip 6 Foldable',
        'Phones',
        89999.0,
        '₹',
        16,
        'Pocket-sized foldable phone with 50MP camera, FlexWindow for hands-free selfies, and enhanced Armor Aluminum hinge.',
        '{"processor": "Snapdragon 8 Gen 3", "ram": "12GB", "storage": "256GB", "camera": "50MP Dual Camera", "display": "6.7-inch FHD+ Dynamic AMOLED 2X + 3.4-inch FlexWindow"}',
        '/images/products/PHN-006.jpg'
    ),
    (
        'PHN-007',
        'Nothing Phone (2) Glyph Edition',
        'Phones',
        37999.0,
        '₹',
        28,
        'Iconic transparent rear aesthetics with customizable Glyph light interface, clean Nothing OS 2.5, and 4700mAh battery.',
        '{"processor": "Snapdragon 8+ Gen 1", "ram": "12GB", "storage": "256GB", "camera": "50MP Sony IMX890 Dual Camera", "display": "6.7-inch LTPO OLED 120Hz", "glyph": "Custom LED Glyph Matrix"}',
        '/images/products/PHN-007.jpg'
    ),
    (
        'PHN-008',
        'Xiaomi 14 Ultra Leica Camera',
        'Phones',
        79999.0,
        '₹',
        14,
        'Professional photography phone with 1-inch variable aperture LYT-900 sensor and quad Leica optical lenses.',
        '{"processor": "Snapdragon 8 Gen 3", "ram": "16GB", "storage": "512GB", "camera": "Quad 50MP Leica Summilux with 1-inch sensor", "display": "6.73-inch 2K WQHD+ AMOLED 120Hz"}',
        '/images/products/PHN-008.jpg'
    ),
    (
        'PHN-009',
        'Vivo X100 Pro Zeiss Optics',
        'Phones',
        64999.0,
        '₹',
        20,
        'Zeiss APO floating telephoto lens, dedicated V3 imaging chip, and cinematic portrait video at 4K.',
        '{"processor": "MediaTek Dimensity 9300", "ram": "16GB", "storage": "512GB", "camera": "50MP 1-inch Main + 50MP Zeiss APO Telephoto", "battery": "5400mAh 100W FlashCharge"}',
        '/images/products/PHN-009.jpg'
    ),
    (
        'PHN-010',
        'Realme GT 6 AI Flagship Killer',
        'Phones',
        39999.0,
        '₹',
        35,
        'Record-breaking 6000-nit ultra-bright OLED display, Snapdragon 8s Gen 3, and 120W fast charging.',
        '{"processor": "Snapdragon 8s Gen 3", "ram": "12GB", "storage": "256GB", "camera": "50MP Sony LYT-808 OIS", "display": "6.78-inch 6000-nit Ultra Bright OLED", "charging": "120W Ultra Charge"}',
        '/images/products/PHN-010.jpg'
    ),
    (
        'HDP-001',
        'Sony WH-1000XM5 Noise Cancelling Headphones',
        'Headphones',
        29990.0,
        '₹',
        24,
        'Benchmark active noise cancellation with 8 microphones, ultra-comfortable soft fit leather, and crystal-clear call quality.',
        '{"anc": "Industry-leading Dual Processor V1 + QN1 ANC", "battery": "30 hours with fast charge", "drivers": "30mm Carbon Fiber composite", "connectivity": "Multipoint Bluetooth 5.2 + LDAC"}',
        '/images/products/HDP-001.jpg'
    ),
    (
        'HDP-002',
        'Apple AirPods Max Space Gray',
        'Headphones',
        59900.0,
        '₹',
        12,
        'High-fidelity audio with custom acoustic design, stainless steel frame, computational audio, and Digital Crown control.',
        '{"chip": "Apple H1 chip in each cup", "anc": "Pro-level Active Noise Cancellation", "audio": "Personalized Spatial Audio with dynamic head tracking", "canopy": "Breathable knit mesh canopy"}',
        '/images/products/HDP-002.jpg'
    ),
    (
        'HDP-003',
        'Bose QuietComfort Ultra Wireless Headphones',
        'Headphones',
        35900.0,
        '₹',
        16,
        'Breakthrough spatialized audio with CustomTune sound calibration tailored to your ear shape and plush protein leather cushions.',
        '{"anc": "World-class CustomTune ANC", "audio": "Bose Immersive Spatial Audio", "battery": "Up to 24 hours (18 with Immersive)", "modes": "Quiet, Aware, and Immersion Modes"}',
        '/images/products/HDP-003.jpg'
    ),
    (
        'HDP-004',
        'Sennheiser Momentum 4 Wireless',
        'Headphones',
        26990.0,
        '₹',
        20,
        'Audiophile sound signature with unmatched 60-hour battery life, customizable EQ, and streamlined lightweight design.',
        '{"drivers": "42mm audiophile-inspired transducer system", "battery": "Exceptional 60 hours playback", "anc": "Adaptive Noise Cancellation & Transparency", "codecs": "aptX Adaptive, AAC, SBC"}',
        '/images/products/HDP-004.jpg'
    ),
    (
        'HDP-005',
        'Marshall Major IV Wireless Bluetooth',
        'Headphones',
        12999.0,
        '₹',
        30,
        'Iconic vintage rock-and-roll styling with explosive bass, multi-directional control knob, and over 80 hours of cord-free music.',
        '{"battery": "80+ hours wireless playtime", "drivers": "40mm dynamic drivers", "charging": "Wireless charging + USB-C fast charge", "design": "Vintage textured vinyl foldable"}',
        '/images/products/HDP-005.jpg'
    ),
    (
        'HDP-006',
        'Sony WF-1000XM5 True Wireless Earbuds',
        'Headphones',
        19990.0,
        '₹',
        25,
        'World-class noise cancelling in an ultralight compact earbud with AI-based noise reduction algorithm and Hi-Res Audio wireless.',
        '{"anc": "Integrated Processor V2 + HD Noise Cancelling QN2e", "drivers": "8.4mm Dynamic Driver X", "battery": "Up to 24 hours with case", "waterproof": "IPX4 water-resistant"}',
        '/images/products/HDP-006.jpg'
    ),
    (
        'HDP-007',
        'Apple AirPods Pro 2 USB-C',
        'Headphones',
        24900.0,
        '₹',
        35,
        'Next-level active noise cancellation, Adaptive Transparency, personalized spatial audio, and USB-C MagSafe charging case.',
        '{"chip": "Apple H2 headphone chip", "anc": "Up to 2x more Active Noise Cancellation", "audio": "Adaptive Audio + Conversation Awareness", "case": "MagSafe Case USB-C with speaker & lanyard loop"}',
        '/images/products/HDP-007.jpg'
    ),
    (
        'HDP-008',
        'Beats Studio Pro Wireless Over-Ear',
        'Headphones',
        29900.0,
        '₹',
        18,
        'Re-engineered flagship over-ear acoustics with lossless USB-C audio, fully adaptive noise cancelling, and ultra-plush ear cushions.',
        '{"drivers": "Custom 40mm active drivers with near-zero distortion", "audio": "Lossless Audio via USB-C", "battery": "Up to 40 hours", "compatibility": "Native one-touch pairing on iOS & Android"}',
        '/images/products/HDP-008.jpg'
    ),
    (
        'HDP-009',
        'JBL Live 660NC Wireless Over-Ear ANC',
        'Headphones',
        7999.0,
        '₹',
        40,
        'Punchy JBL Signature Sound with deep bass, comfortable fabric headband, fast pairing, and up to 50 hours of battery life.',
        '{"anc": "Adaptive Noise Cancelling with Ambient Aware", "drivers": "40mm signature JBL sound drivers", "battery": "Up to 50 hours (40 with ANC)", "voice": "Alexa and Google Assistant built-in"}',
        '/images/products/HDP-009.jpg'
    ),
    (
        'HDP-010',
        'Razer BlackShark V2 Pro Gaming Headset with Mic',
        'Headphones',
        14999.0,
        '₹',
        22,
        'Professional esports wireless headset with Razer HyperClear Super Wideband mic, TriForce Titanium 50mm drivers, and ultra-soft memory foam.',
        '{"drivers": "TriForce Titanium 50mm", "mic": "HyperClear Super Wideband Detachable Boom Mic", "battery": "Up to 70 hours", "latency": "Ultra-low latency HyperSpeed Wireless"}',
        '/images/products/HDP-010.jpg'
    ),
    (
        'TAB-001',
        'Apple iPad Pro 13" M4 OLED Display',
        'Tablets',
        129900.0,
        '₹',
        15,
        'Impossibly thin design with game-changing Ultra Retina XDR Tandem OLED, Apple M4 chip, and support for Apple Pencil Pro.',
        '{"chip": "Apple M4 9-Core CPU / 10-Core GPU", "storage": "256GB SSD", "display": "13-inch Ultra Retina XDR Tandem OLED 120Hz", "weight": "579g"}',
        '/images/products/TAB-001.jpg'
    ),
    (
        'TAB-002',
        'Samsung Galaxy Tab S10 Ultra 14.6"',
        'Tablets',
        108999.0,
        '₹',
        12,
        'Massive 14.6-inch Dynamic AMOLED 2X display with anti-reflective coating, Galaxy AI, IP68 water resistance, and included S-Pen.',
        '{"processor": "MediaTek Dimensity 9300+", "ram": "12GB", "storage": "256GB", "display": "14.6-inch Dynamic AMOLED 2X 120Hz", "spen": "Included low-latency S-Pen"}',
        '/images/products/TAB-002.jpg'
    ),
    (
        'TAB-003',
        'Apple iPad Air 11" M2 Liquid Retina',
        'Tablets',
        59900.0,
        '₹',
        25,
        'Powered by the blazing-fast M2 chip, 11-inch Liquid Retina display, landscape 12MP front camera with Center Stage, and Wi-Fi 6E.',
        '{"chip": "Apple M2 8-core CPU", "storage": "128GB", "display": "11-inch Liquid Retina with True Tone", "camera": "Landscape 12MP Ultra-wide"}',
        '/images/products/TAB-003.jpg'
    ),
    (
        'TAB-004',
        'Apple iPad 10th Gen 10.9" All-Screen',
        'Tablets',
        34900.0,
        '₹',
        35,
        'Colorfully reimagined all-screen iPad with A14 Bionic, 10.9-inch Liquid Retina display, USB-C, and Touch ID in top button.',
        '{"chip": "A14 Bionic", "storage": "64GB", "display": "10.9-inch Liquid Retina 500 nits", "port": "USB-C"}',
        '/images/products/TAB-004.jpg'
    ),
    (
        'TAB-005',
        'OnePlus Pad 2 3K 144Hz Display',
        'Tablets',
        39999.0,
        '₹',
        20,
        'Powerhouse Android tablet with Snapdragon 8 Gen 3, 12.1-inch 3K 144Hz 7:5 ReadFit display, and 6-speaker spatial audio system.',
        '{"processor": "Snapdragon 8 Gen 3", "ram": "12GB", "storage": "256GB", "display": "12.1-inch 3K 144Hz 7:5 ratio", "charging": "67W SUPERVOOC"}',
        '/images/products/TAB-005.jpg'
    ),
    (
        'TAB-006',
        'Xiaomi Pad 6 Snapdragon 870 Tablet',
        'Tablets',
        26999.0,
        '₹',
        30,
        'Crisp 11-inch 2.8K 144Hz display with Dolby Vision, metal unibody design, quad speakers, and 8840mAh long-lasting battery.',
        '{"processor": "Snapdragon 870", "ram": "8GB", "storage": "256GB", "display": "11-inch 2.8K 144Hz 10-bit", "audio": "Quad Speakers Dolby Atmos"}',
        '/images/products/TAB-006.jpg'
    ),
    (
        'TAB-007',
        'Lenovo Tab P12 Pro with Precision Pen 3',
        'Tablets',
        32990.0,
        '₹',
        18,
        'Productivity tablet with 12.6-inch 2K AMOLED screen, JBL quad speakers, wireless charging stylus, and secondary wireless PC monitor mode.',
        '{"processor": "MediaTek Dimensity 7050", "ram": "8GB", "storage": "128GB", "display": "12.7-inch 3K LTPS LCD", "pen": "Included Precision Pen 3"}',
        '/images/products/TAB-007.jpg'
    ),
    (
        'TAB-008',
        'Apple iPad Mini 7 A17 Pro',
        'Tablets',
        49900.0,
        '₹',
        22,
        'Ultraportable 8.3-inch powerhouse with A17 Pro chip, Apple Intelligence support, Wi-Fi 6E, and fast USB-C data transfer.',
        '{"chip": "A17 Pro", "storage": "128GB", "display": "8.3-inch Liquid Retina True Tone", "weight": "293g"}',
        '/images/products/TAB-008.jpg'
    ),
    (
        'TAB-009',
        'Samsung Galaxy Tab A9+ 5G',
        'Tablets',
        19999.0,
        '₹',
        40,
        'Great family entertainment tablet with 11-inch 90Hz display, quad speakers with Dolby Atmos, 5G SIM slot, and Samsung DeX support.',
        '{"processor": "Snapdragon 695 5G", "ram": "8GB", "storage": "128GB", "display": "11-inch WUXGA 90Hz", "connectivity": "5G Cellular + Wi-Fi"}',
        '/images/products/TAB-009.jpg'
    ),
    (
        'TAB-010',
        'Realme Pad 2 120Hz 11.5"',
        'Tablets',
        15999.0,
        '₹',
        45,
        'Budget champion tablet featuring 11.5-inch 2K 120Hz super display, quad stereo speakers, and 8360mAh battery with 33W SUPERVOOC.',
        '{"processor": "MediaTek Helio G99", "ram": "6GB", "storage": "128GB", "display": "11.5-inch 2K 120Hz", "battery": "8360mAh 33W Fast Charge"}',
        '/images/products/TAB-010.jpg'
    ),
    (
        'CAM-001',
        'Sony Alpha 7 IV Full-Frame Mirrorless',
        'Cameras',
        214990.0,
        '₹',
        10,
        'Industry standard hybrid camera with 33MP Exmor R sensor, BIONZ XR engine, 4K 60p 10-bit recording, and real-time eye autofocus.',
        '{"sensor": "33MP Full-Frame Exmor R CMOS", "video": "4K 60p 10-bit 4:2:2", "autofocus": "759-point Phase Detection AF", "stabilization": "5-axis In-body Optical IS"}',
        '/images/products/CAM-001.jpg'
    ),
    (
        'CAM-002',
        'Canon EOS R6 Mark II 4K 60p',
        'Cameras',
        229995.0,
        '₹',
        8,
        'Speed master mirrorless camera capturing up to 40fps electronic shutter, 6K oversampled 4K 60p video, and Dual Pixel CMOS AF II.',
        '{"sensor": "24.2MP Full-Frame CMOS", "speed": "Up to 40 fps electronic", "video": "6K Oversampled 4K 60p uncropped", "ibis": "Up to 8 stops Image Stabilization"}',
        '/images/products/CAM-002.jpg'
    ),
    (
        'CAM-003',
        'Fujifilm X-T5 Mirrorless Camera',
        'Cameras',
        169999.0,
        '₹',
        12,
        'Classic dial-based photography masterpiece with 40.2MP X-Trans CMOS 5 HR sensor, 6.2K 30p video, and 7.0 stops 5-axis IBIS.',
        '{"sensor": "40.2MP X-Trans 5 HR", "video": "6.2K 30p 4:2:2 10-bit", "ibis": "7-stop 5-axis In-Body Stabilization", "simulations": "19 Film Simulation modes"}',
        '/images/products/CAM-003.jpg'
    ),
    (
        'CAM-004',
        'Nikon Z6 III 24.5MP Full Frame',
        'Cameras',
        199990.0,
        '₹',
        10,
        'Partially-stacked full-frame sensor offering 6K 60p N-RAW internal recording, ultra-bright 4000-nit EVF, and advanced subject detection.',
        '{"sensor": "24.5MP Partially-Stacked CMOS", "video": "6K 60p N-RAW internal", "evf": "5.76M-dot 4000-nit HDR EVF", "speed": "Up to 120 fps burst"}',
        '/images/products/CAM-004.jpg'
    ),
    
    (
        'CAM-006',
        'DJI Osmo Pocket 3 Creator Combo',
        'Cameras',
        53990.0,
        '₹',
        16,
        'Pocket-sized handheld camera featuring a 1-inch CMOS sensor, 3-axis mechanical gimbal, 2-inch rotatable OLED screen, and wireless mic.',
        '{"sensor": "1-inch CMOS sensor", "gimbal": "3-axis Mechanical Stabilization", "video": "4K 120fps D-Log M 10-bit", "audio": "Included DJI Mic 2 Wireless Transmitter"}',
        '/images/products/CAM-006.jpg'
    ),
    
    (
        'CAM-008',
        'Panasonic Lumix S5 II Mirrorless',
        'Cameras',
        149990.0,
        '₹',
        14,
        'Full-frame powerhouse with Phase Hybrid AF, unlimited 4K 60p recording with built-in cooling fan, and Active I.S. video walking stabilization.',
        '{"sensor": "24.2MP Full-Frame CMOS", "af": "Phase Hybrid AF with 779 points", "cooling": "Built-in fan for unlimited 4K recording", "ibis": "Active I.S. gimbal-like stabilization"}',
        '/images/products/CAM-008.jpg'
    ),
    (
        'CAM-009',
        'Insta360 X4 8K 360 Action Camera',
        'Cameras',
        49990.0,
        '₹',
        18,
        'Next-generation 8K 30fps 360-degree action camera with Invisible Selfie Stick effect, FlowState stabilization, and replaceable lens guards.',
        '{"resolution": "8K 30fps / 5.7K 60fps 360 Video", "stabilization": "FlowState + 360 Horizon Lock", "waterproof": "10m / 33ft", "features": "AI-powered reframing & gesture control"}',
        '/images/products/CAM-009.jpg'
    ),
    (
        'CAM-010',
        'Canon EOS 1500D DSLR Starter Kit',
        'Cameras',
        41990.0,
        '₹',
        24,
        'Classic entry-level DSLR camera with 24.1MP APS-C CMOS sensor, optical viewfinder, EF-S 18-55mm IS II lens, and built-in Wi-Fi NFC.',
        '{"sensor": "24.1MP APS-C CMOS", "lens": "EF-S 18-55mm f/3.5-5.6 IS II", "viewfinder": "Optical Pentamirror 95% coverage", "connectivity": "Wi-Fi & NFC"}',
        '/images/products/CAM-010.jpg'
    ),
    (
        'ACC-001',
        'Logitech MX Master 3S Wireless Performance Mouse',
        'Accessories',
        8995.0,
        '₹',
        45,
        'Ergonomic precision mouse with 8K DPI tracking on glass, electromagnetic scroll wheel, and customizable gesture buttons.',
        '{"sensor": "Darkfield 8000 DPI", "scroll": "MagSpeed Electromagnetic", "clicks": "Quiet Click 90% reduced noise", "battery": "Up to 70 days USB-C"}',
        '/images/products/ACC-001.jpg'
    ),
    (
        'ACC-002',
        'Apple AirPods 3rd Generation with MagSafe Case',
        'Accessories',
        19900.0,
        '₹',
        30,
        'Contoured wireless AirPods with force sensor controls, adaptive EQ, personalized spatial audio, and MagSafe charging.',
        '{"audio": "Personalized Spatial Audio with dynamic head tracking", "battery": "Up to 30 hours with case", "sweat_resistant": "IPX4 sweat and water resistant"}',
        '/images/products/ACC-002.jpg'
    ),
    (
        'ACC-003',
        'Keychron K2 Pro Wireless Mechanical Keyboard',
        'Accessories',
        9499.0,
        '₹',
        28,
        'Custom 75% wireless mechanical keyboard with sound-absorbing foam, double-shot PBT keycaps, and south-facing RGB backlighting.',
        '{"layout": "75% Compact 84 keys", "switches": "Hot-swappable K Pro Red", "backlight": "South-facing RGB", "connectivity": "Bluetooth 5.1 & Type-C"}',
        '/images/products/ACC-003.jpg'
    ),
    (
        'ACC-004',
        'Razer DeathAdder V3 Pro Wireless Gaming Mouse',
        'Accessories',
        13999.0,
        '₹',
        22,
        'Ultra-lightweight 63g ergonomic esports mouse with Focus Pro 30K Optical Sensor, Gen-3 optical switches, and 90-hour battery life.',
        '{"sensor": "Focus Pro 30K Optical", "weight": "63 grams Ultra-Light", "polling_rate": "True 4000Hz compatible", "battery": "Up to 90 hours"}',
        '/images/products/ACC-004.jpg'
    ),
    (
        'ACC-005',
        'Logitech Brio 4K Ultra HD Pro Stream Webcam',
        'Accessories',
        18995.0,
        '₹',
        25,
        'Premium 4K HDR streaming and conference webcam with RightLight 3 light correction, dual omnidirectional noise-cancelling mics, and Windows Hello.',
        '{"resolution": "4K Ultra HD at 30fps / 1080p at 60fps", "hdr": "RightLight 3 with HDR", "fov": "Adjustable 65, 78, 90-degree field of view", "security": "Infrared facial recognition login"}',
        '/images/products/ACC-005.jpg'
    ),
    (
        'ACC-006',
        'Corsair K70 RGB Mechanical Gaming Keyboard',
        'Accessories',
        11499.0,
        '₹',
        24,
        'Anodized brushed aluminum frame with Cherry MX mechanical key switches, per-key dynamic RGB backlighting, and dedicated media controls with volume roller.',
        '{"switches": "Cherry MX Speed Silver 1.2mm actuation", "frame": "Aircraft-grade Brushed Aluminum", "lighting": "Per-Key Dynamic RGB", "wrist_rest": "Detachable soft-touch palm rest"}',
        '/images/products/ACC-006.jpg'
    ),
    (
        'ACC-007',
        'Logitech MX Anywhere 3S Compact Travel Mouse',
        'Accessories',
        6995.0,
        '₹',
        35,
        'Pocket-sized ultra-fast wireless mouse designed for mobile workstations with 8K DPI glass sensor and silent electromagnetic scroll wheel.',
        '{"sensor": "8000 DPI track-anywhere optical", "weight": "99g travel friendly", "connectivity": "Bluetooth Low Energy & Logi Bolt", "battery": "Up to 70 days per charge"}',
        '/images/products/ACC-007.jpg'
    ),
    (
        'ACC-008',
        'CalDigit TS4 Thunderbolt 4 18-Port Workstation Dock',
        'Accessories',
        34999.0,
        '₹',
        15,
        'The ultimate single-cable workstation dock with 98W laptop charging, 2.5GbE LAN, dual 6K display support, 8 USB ports, and UHS-II SD reader.',
        '{"ports": "18 Total Connectivity Ports", "charging": "98W Host Power Delivery", "displays": "Up to Dual 6K 60Hz or Single 8K", "ethernet": "2.5 Gigabit Ethernet LAN"}',
        '/images/products/ACC-008.jpg'
    ),
]
